export const ERROR_MESSAGE = {
  BAD_REQUEST: "Bad request",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  NOT_FOUND: "Not found",
  INTERNAL_SERVER_ERROR: "Internal server error",
  INVALID_INPUT: "Invalid input",
  SOMETHING_WENT_WRONG: "Something went wrong",
  TOKEN_MISSING: "Authentication token missing",
  INVALID_TOKEN: "Invalid or expired token",
  INVALID_CREDENTIALS: "Invalid credentials",
  INVALID_PASSWORD: "Invalid password",
  USER_NOT_FOUND: "User not found",
  USER_EXISTS: "User already exists",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  PASSWORD_EMPTY: "Password should not be empty",
  SCHEMA_VALIDATION_FAILED: "Schema validation failed",
  MISSING_REQUIRED_FIELD_DATA: "Mandatory fields missing",
  INVALID_OPERATION: "Invalid operation",
  TOO_MANY_REQUESTS: "Too many requests, please try again later",
};
